# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  displayName: 'Set node version'
  inputs:
    version: '10.15.3'

- task: Npm@1
  displayName: 'Resolve dependencies'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: CopyFiles@2
  displayName: 'Copy Static Files'
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)'
    contents: |
      web/public/**/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    overwrite: true

- task: PublishBuildArtifacts@1
  displayName: Publish
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'